// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNh7GlfqMOqpfBaqe9MCdeA-XNl1e4oE0',
    appId: '1:652163409265:web:6581e5abcc6e92219142d0',
    messagingSenderId: '652163409265',
    projectId: 'notifyweather-b7d57',
    authDomain: 'notifyweather-b7d57.firebaseapp.com',
    storageBucket: 'notifyweather-b7d57.firebasestorage.app',
    measurementId: 'G-VBFWD0B3WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARi-O4hl66xm0D6PULCR-x6oz-77LWYOE',
    appId: '1:652163409265:android:455907738c181b519142d0',
    messagingSenderId: '652163409265',
    projectId: 'notifyweather-b7d57',
    storageBucket: 'notifyweather-b7d57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNzESadF3iYGndU5vgBfc9POEWnsLPq4M',
    appId: '1:652163409265:ios:e44309f2544086119142d0',
    messagingSenderId: '652163409265',
    projectId: 'notifyweather-b7d57',
    storageBucket: 'notifyweather-b7d57.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNzESadF3iYGndU5vgBfc9POEWnsLPq4M',
    appId: '1:652163409265:ios:e44309f2544086119142d0',
    messagingSenderId: '652163409265',
    projectId: 'notifyweather-b7d57',
    storageBucket: 'notifyweather-b7d57.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNh7GlfqMOqpfBaqe9MCdeA-XNl1e4oE0',
    appId: '1:652163409265:web:9835598c42a09bda9142d0',
    messagingSenderId: '652163409265',
    projectId: 'notifyweather-b7d57',
    authDomain: 'notifyweather-b7d57.firebaseapp.com',
    storageBucket: 'notifyweather-b7d57.firebasestorage.app',
    measurementId: 'G-15BPC4Q9QW',
  );
}
